### ISSUE TITLE
No needed item

### ISSUE THREAD

**Issue by yusufobr** [Bestbynature/portfolio#9]
https://github.com/Bestbynature/portfolio/blob/49351eb74f4557a975bde3af4324003d0f7fbda0/index.html#L152

Kindly make sure to remove the cursor icon, because the design expects you to add a `hover ` effect.

**Comment by Bestbynature** [comment]
> https://github.com/Bestbynature/portfolio/blob/49351eb74f4557a975bde3af4324003d0f7fbda0/index.html#L152
> 
> Kindly make sure to remove the cursor icon, because the design expects you to add a `hover ` effect.

Thanks @mahabubx7, The change has been implemented as suggested.
